version: '3'

services:
  airmate_api:
    volumes:
      - airmate_api_logs:/data_layer/logs
    build: data_layer
    restart: always
    command: bash -c "FLASK_APP=api flask db upgrade && gunicorn --bind 0.0.0.0:5000 api.wsgi:app"
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - dev

  airmate_web:
    build: web
    restart: always
    ports:
    - "80:3000"
    depends_on:
    - airmate_api
    networks:
    - dev

  db:
    image: postgres
    restart: always
    env_file: .env
    ports:
    - "5432"
    networks:
    - dev

  openaq_watchdog:
    build: data_layer
    restart: always
    command: bash -c "cd third_party && python openaq_watchdog.py"
    depends_on:
    - db
    networks:
    - dev

#  minimax_watchdog:
#    build: data_layer
#    env_file: .env
#    restart: always
#    command: bash -c "cd third_party && python minimax_watchdog.py"
#    depends_on:
#    - db
#    networks:
#    - dev

networks:
  dev:

volumes:
  airmate_api_logs:
    driver: local