version: '2'

services:
  mysql:
    restart: always
    image: mysql:5.7
    expose:
      - "3306"
    ports:
     - "3306:3306"
    volumes:
      - ./config:/etc/mysql/conf.d:ro
      - mysql:/var/lib/mysql
      - ./config/:/docker-entrypoint-initdb.d
    environment:
      LANG: "C.UTF-8"
      MYSQL_USER: innosoft
      MYSQL_PASSWORD: innosoft
      MYSQL_ROOT_PASSWORD: innosoft

  bigchaindb:
    restart: always
    image: bigchaindb/bigchaindb
#    entrypoint: /bin/bash
#    command: /init/init_bigchain.sh
    command: start
    ports:
     - "9984:9984"
    volumes:
      - ./bigchaindb_data:/data
      - ./init:/init
    links:
      - mongodb
    depends_on:
      - mongodb

  mongodb:
    restart: always
    image: mongo

volumes:
  mysql:
    driver: local
